In [9]:
#import libraries 
import requests
import json
import pandas as pd

In [26]:
#dataframe list will hold all the databases created from the main function and for loop 
dataframe_lists = []

#query list is for all the queries that the api will pull up data on  
Query_list = ['AAPL:NASDAQ', 'GOOGL:NASDAQ', 'TSLA:NASDAQ', 'NFLX:NASDAQ', 'AMZN:NASDAQ', 'NVDA:NASDAQ', 'AAL:NASDAQ', 'SOFI:NASDAQ', 'AMD:NASDAQ', 'PTON:NASDAQ', ]

#this function makes a request to the api with a specific query then returns a dataframe that contains all the informaion that the api gives 
def main(x):
  url = "https://real-time-finance-data.p.rapidapi.com/stock-quote"

  querystring = {"symbol":x,"language":"en"}

  headers = {
    "X-RapidAPI-Key": "f43bae6fb8msh9a980c6829caa63p119daejsne54b0a778b9c",
    "X-RapidAPI-Host": "real-time-finance-data.p.rapidapi.com"
  }

  response = requests.request("GET", url, headers=headers, params=querystring)

  data = response.json()

  df = pd.DataFrame(data['data'], index = ["-"])
  return df 

#for loop runs the function for each query in the query list, then appends the resulting database to 'dataframe_lists' 
for x in Query_list:
  dataframe_lists.append(main(x))

In [27]:
#the.concat function combines all the dataframes in 'dataframe_lists' into one single dataframe 
concat_dataframes = pd.concat(dataframe_lists)

#exporting the dataframe to csv file 
concat_dataframes.to_csv ('concat_dataframes.csv', index = False)
concat_dataframes

,symbol,name,type,price,open,high,low,volume,previous_close,change,change_percent,pre_or_post_market,pre_or_post_market_change,pre_or_post_market_change_percent,last_update_utc
-,AAPL:NASDAQ,Apple Inc,stock,160.2800,161.220,162.0600,159.7800,35494306,160.80,-0.5200,-0.3234,161.21,0.9800,0.6116,2023-04-12 19:35:46
-,GOOGL:NASDAQ,Alphabet Inc Class A,stock,104.6337,106.580,106.7500,104.3400,17118839,105.35,-0.7163,-0.6799,106.54,1.8800,1.7963,2023-04-12 19:35:45
-,TSLA:NASDAQ,Tesla Inc,stock,181.1300,190.740,191.5846,180.3200,133648256,186.79,-5.6600,-3.0301,190.95,10.1284,5.6013,2023-04-12 19:35:48
-,NFLX:NASDAQ,Netflix Inc,stock,331.4050,340.810,342.8000,330.5600,2699184,338.21,-6.8050,-2.0121,341.64,10.8000,3.2644,2023-04-12 19:35:47
-,AMZN:NASDAQ,"Amazon.com, Inc.",stock,98.1500,100.400,100.5100,97.8800,42793201,99.92,-1.7700,-1.7714,100.45,2.4250,2.4739,2023-04-12 19:35:47
-,NVDA:NASDAQ,NVIDIA Corporation,stock,265.6200,273.700,274.6799,264.4786,37665464,271.69,-6.0700,-2.2342,273.50,8.7800,3.3167,2023-04-12 19:35:50
-,AAL:NASDAQ,American Airlines Group Inc,stock,12.9650,13.850,13.8500,12.9100,81188298,14.32,-1.3550,-9.4623,13.82,0.8750,6.7594,2023-04-12 19:35:58
-,SOFI:NASDAQ,SoFi Technologies Inc,stock,5.8379,6.060,6.0600,5.6700,32004782,5.97,-0.1321,-2.2127,6.06,0.2300,3.9451,2023-04-12 19:35:53
-,AMD:NASDAQ,"Advanced Micro Devices, Inc.",stock,92.4700,94.970,95.0000,91.7400,46067145,94.03,-1.5600,-1.6590,94.87,2.4000,2.5954,2023-04-12 19:35:30
-,PTON:NASDAQ,Peloton Interactive Inc,stock,10.2085,11.665,11.6700,10.0100,13574147,11.49,-1.2815,-11.1532,11.70,1.5123,14.8444,2023-04-12 19:35:50

In [21]:
#getting the descriptive staistics for the dataframe using the .describe function 
concat_dataframes.describe()

,price,open,high,low,volume,previous_close,change,change_percent,pre_or_post_market,pre_or_post_market_change,pre_or_post_market_change_percent
count,10.000000,10.00000,10.000000,10.000000,1.000000e+01,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,126.202320,129.99950,130.496450,125.959010,4.292158e+07,128.857000,-2.654680,-3.491190,130.074000,3.735460,4.395510
std,110.023762,113.16726,113.785038,109.954752,3.692970e+07,112.152839,2.551215,3.626035,113.325563,3.763255,3.835517
min,5.838200,6.06000,6.060000,5.670000,2.538595e+06,5.970000,-6.470000,-10.748500,6.060000,0.245000,0.417300
25%,32.716250,34.13000,34.137500,32.617500,2.014695e+07,34.247500,-4.996250,-3.002475,34.082500,1.030000,2.489175
50%,101.415000,103.49000,103.630000,101.195000,3.528882e+07,102.635000,-1.562500,-2.167350,103.495000,2.073550,3.057350
75%,175.651250,183.36000,184.203450,175.270000,4.410462e+07,180.292500,-0.826250,-1.780725,183.515000,6.740000,5.098725
max,331.890000,340.81000,342.800000,331.630000,1.293441e+08,338.210000,-0.131800,-0.360700,341.640000,9.772500,13.979500